export const QUESTIONS = [
  {
    id: "ph-1",
    question: "What is the capital city of the Philippines?",
    options: ["Cebu City", "Davao City", "Manila", "Quezon City"],
    correctAnswerIndex: 2,
    difficulty: 1,
  },
  {
    id: "ph-2",
    question: "Who is the national hero of the Philippines?",
    options: ["Andres Bonifacio", "Emilio Aguinaldo", "Jose Rizal", "Apolinario Mabini"],
    correctAnswerIndex: 2,
    difficulty: 1,
  },
  {
    id: "ph-3",
    question: "What is the national language of the Philippines?",
    options: ["English", "Spanish", "Filipino", "Cebuano"],
    correctAnswerIndex: 2,
    difficulty: 1,
  },
  {
    id: "ph-4",
    question: "Which is the largest island in the Philippines?",
    options: ["Luzon", "Visayas", "Mindanao", "Palawan"],
    correctAnswerIndex: 0,
    difficulty: 1,
  },
  {
    id: "ph-5",
    question: "What is the currency of the Philippines?",
    options: ["Dollar", "Peso", "Yen", "Baht"],
    correctAnswerIndex: 1,
    difficulty: 1,
  },
  {
    id: "ph-6",
    question: "When is Philippine Independence Day celebrated?",
    options: ["May 1", "June 12", "August 21", "December 30"],
    correctAnswerIndex: 1,
    difficulty: 2,
  },
  {
    id: "ph-7",
    question: "Who was the first President of the Philippines?",
    options: ["Manuel L. Quezon", "Sergio Osmeña", "Emilio Aguinaldo", "Ferdinand Marcos"],
    correctAnswerIndex: 2,
    difficulty: 2,
  },
  {
    id: "ph-8",
    question: "What is the national bird of the Philippines?",
    options: ["Eagle", "Maya", "Philippine Eagle", "Hawk"],
    correctAnswerIndex: 2,
    difficulty: 2,
  },
  {
    id: "ph-9",
    question: "Which ocean is located east of the Philippines?",
    options: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"],
    correctAnswerIndex: 1,
    difficulty: 2,
  },
  {
    id: "ph-10",
    question: "What is the famous rice terraces found in the Philippines?",
    options: ["Banaue Rice Terraces", "Chocolate Hills", "Mayon Volcano", "Taal Lake"],
    correctAnswerIndex: 0,
    difficulty: 2,
  },
];
